"""added fields like date and text

Revision ID: 673c9e387cb3
Revises: 0344532a684e
Create Date: 2025-09-27 17:10:47.546355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '673c9e387cb3'
down_revision: Union[str, Sequence[str], None] = '0344532a684e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio', sa.Column('creation_date', sa.Date(), nullable=False))
    op.add_column('audio', sa.Column('duration', sa.Float(), nullable=False))
    op.add_column('audio', sa.Column('text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio', 'text')
    op.drop_column('audio', 'duration')
    op.drop_column('audio', 'creation_date')
    # ### end Alembic commands ###
